-- ============================================================================
-- Initial schema migration for the web/Supabase port of Inventory Tracking App.
-- Translated from the SQLite schema in src/app/services/database.service.ts
-- (the offline Capacitor version).
--
-- Key changes vs SQLite:
--   * Drops `users` and `sessions` tables - replaced by Supabase Auth (auth.users)
--   * Every per-user table uses uuid user_id referencing auth.users
--   * boolean instead of INTEGER 0/1
--   * timestamptz instead of TEXT/DATETIME
--   * Adds missing indexes flagged in the security audit
--   * Adds UNIQUE(user_id, plan_date, meal_type) to fix the duplicate-slot
--     bug found in the uncommitted meal-plan diff
--   * RLS enabled on every per-user table with owner-only policies
-- ============================================================================

create extension if not exists "pgcrypto";

-- ----------------------------------------------------------------------------
-- categories  (global read-only seed)
-- ----------------------------------------------------------------------------
create table public.categories (
  id      bigint generated by default as identity primary key,
  name    text not null unique,
  icon    text,
  color   text
);

alter table public.categories enable row level security;

-- Anyone (authenticated) can read categories. No write policies = no client writes.
create policy "categories_read_authenticated"
  on public.categories for select
  to authenticated
  using (true);

-- ----------------------------------------------------------------------------
-- locations  (per user)
-- ----------------------------------------------------------------------------
create table public.locations (
  id            bigint generated by default as identity primary key,
  user_id       uuid not null references auth.users(id) on delete cascade,
  name          text not null,
  sub_location  text,
  created_at    timestamptz not null default now()
);

create index idx_locations_user on public.locations(user_id);

alter table public.locations enable row level security;
create policy "locations_owner_select" on public.locations for select using (auth.uid() = user_id);
create policy "locations_owner_insert" on public.locations for insert with check (auth.uid() = user_id);
create policy "locations_owner_update" on public.locations for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "locations_owner_delete" on public.locations for delete using (auth.uid() = user_id);

-- ----------------------------------------------------------------------------
-- inventory_items
-- ----------------------------------------------------------------------------
create table public.inventory_items (
  id                       bigint generated by default as identity primary key,
  user_id                  uuid not null references auth.users(id) on delete cascade,
  name                     text not null,
  category_id              bigint not null references public.categories(id),
  quantity                 numeric not null default 0,
  unit                     text not null,
  purchase_date            date,
  expiration_date          date not null,
  location_id              bigint references public.locations(id) on delete set null,
  price                    numeric,
  notes                    text,
  notification_enabled     boolean not null default true,
  notification_days_before integer not null default 3,
  barcode                  text,
  initial_quantity         numeric,
  current_quantity         numeric,
  usage_notes              text,
  low_stock_threshold      numeric default 20,
  created_at               timestamptz not null default now(),
  updated_at               timestamptz not null default now()
);

create index idx_inventory_user        on public.inventory_items(user_id);
create index idx_inventory_expiry      on public.inventory_items(expiration_date);
create index idx_inventory_user_expiry on public.inventory_items(user_id, expiration_date);
create index idx_inventory_category    on public.inventory_items(category_id);
create index idx_inventory_location    on public.inventory_items(location_id);
create unique index uq_inventory_user_barcode on public.inventory_items(user_id, barcode) where barcode is not null;

alter table public.inventory_items enable row level security;
create policy "inventory_owner_select" on public.inventory_items for select using (auth.uid() = user_id);
create policy "inventory_owner_insert" on public.inventory_items for insert with check (auth.uid() = user_id);
create policy "inventory_owner_update" on public.inventory_items for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "inventory_owner_delete" on public.inventory_items for delete using (auth.uid() = user_id);

-- ----------------------------------------------------------------------------
-- inventory_batches  (multiple batches per item, FIFO consumption)
-- ----------------------------------------------------------------------------
create table public.inventory_batches (
  id              bigint generated by default as identity primary key,
  item_id         bigint not null references public.inventory_items(id) on delete cascade,
  user_id         uuid not null references auth.users(id) on delete cascade,
  quantity        numeric not null,
  expiration_date date,
  purchase_date   date not null,
  price           numeric,
  notes           text,
  created_at      timestamptz not null default now()
);

create index idx_batches_item            on public.inventory_batches(item_id);
create index idx_batches_user            on public.inventory_batches(user_id);
create index idx_batches_expiry          on public.inventory_batches(expiration_date);
create index idx_batches_user_item_expiry on public.inventory_batches(user_id, item_id, expiration_date);

alter table public.inventory_batches enable row level security;
create policy "batches_owner_select" on public.inventory_batches for select using (auth.uid() = user_id);
create policy "batches_owner_insert" on public.inventory_batches for insert with check (auth.uid() = user_id);
create policy "batches_owner_update" on public.inventory_batches for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "batches_owner_delete" on public.inventory_batches for delete using (auth.uid() = user_id);

-- ----------------------------------------------------------------------------
-- item_images  (paths in Supabase Storage bucket `inventory-images`)
-- ----------------------------------------------------------------------------
create table public.item_images (
  id          bigint generated by default as identity primary key,
  item_id     bigint not null references public.inventory_items(id) on delete cascade,
  user_id     uuid not null references auth.users(id) on delete cascade,
  storage_path text not null,
  is_primary  boolean not null default false,
  created_at  timestamptz not null default now()
);

create index idx_images_item on public.item_images(item_id);
create index idx_images_user on public.item_images(user_id);

alter table public.item_images enable row level security;
create policy "images_owner_select" on public.item_images for select using (auth.uid() = user_id);
create policy "images_owner_insert" on public.item_images for insert with check (auth.uid() = user_id);
create policy "images_owner_update" on public.item_images for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "images_owner_delete" on public.item_images for delete using (auth.uid() = user_id);

-- ----------------------------------------------------------------------------
-- shopping_list
-- ----------------------------------------------------------------------------
create table public.shopping_list (
  id            bigint generated by default as identity primary key,
  user_id       uuid not null references auth.users(id) on delete cascade,
  name          text not null,
  quantity      text,
  notes         text,
  category_id   bigint references public.categories(id),
  is_purchased  boolean not null default false,
  created_at    timestamptz not null default now()
);

create index idx_shopping_user on public.shopping_list(user_id);

alter table public.shopping_list enable row level security;
create policy "shopping_owner_select" on public.shopping_list for select using (auth.uid() = user_id);
create policy "shopping_owner_insert" on public.shopping_list for insert with check (auth.uid() = user_id);
create policy "shopping_owner_update" on public.shopping_list for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "shopping_owner_delete" on public.shopping_list for delete using (auth.uid() = user_id);

-- ----------------------------------------------------------------------------
-- wasted_items
-- ----------------------------------------------------------------------------
create table public.wasted_items (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null references auth.users(id) on delete cascade,
  item_name   text not null,
  category_id bigint references public.categories(id),
  quantity    numeric not null,
  unit        text not null,
  price       numeric,
  wasted_date timestamptz not null default now()
);

create index idx_wasted_user on public.wasted_items(user_id);
create index idx_wasted_user_date on public.wasted_items(user_id, wasted_date desc);

alter table public.wasted_items enable row level security;
create policy "wasted_owner_select" on public.wasted_items for select using (auth.uid() = user_id);
create policy "wasted_owner_insert" on public.wasted_items for insert with check (auth.uid() = user_id);
create policy "wasted_owner_update" on public.wasted_items for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "wasted_owner_delete" on public.wasted_items for delete using (auth.uid() = user_id);

-- ----------------------------------------------------------------------------
-- usage_history
-- ----------------------------------------------------------------------------
create table public.usage_history (
  id               bigint generated by default as identity primary key,
  item_id          bigint not null references public.inventory_items(id) on delete cascade,
  user_id          uuid not null references auth.users(id) on delete cascade,
  amount_used      numeric not null,
  remaining_amount numeric not null,
  notes            text,
  recorded_at      timestamptz not null default now()
);

create index idx_usage_item on public.usage_history(item_id);
create index idx_usage_user on public.usage_history(user_id);

alter table public.usage_history enable row level security;
create policy "usage_owner_select" on public.usage_history for select using (auth.uid() = user_id);
create policy "usage_owner_insert" on public.usage_history for insert with check (auth.uid() = user_id);
create policy "usage_owner_update" on public.usage_history for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "usage_owner_delete" on public.usage_history for delete using (auth.uid() = user_id);

-- ----------------------------------------------------------------------------
-- barcode_mappings  (per user; offline learn-as-you-go barcode database)
-- ----------------------------------------------------------------------------
create table public.barcode_mappings (
  id                         bigint generated by default as identity primary key,
  user_id                    uuid not null references auth.users(id) on delete cascade,
  barcode                    text not null,
  item_name                  text not null,
  category_id                bigint not null references public.categories(id),
  location_id                bigint references public.locations(id) on delete set null,
  price                      numeric,
  suggested_shelf_life_days  integer,
  ai_note                    text,
  image_path                 text,
  created_at                 timestamptz not null default now(),
  unique (user_id, barcode)
);

create index idx_barcode_user on public.barcode_mappings(user_id);

alter table public.barcode_mappings enable row level security;
create policy "barcode_owner_select" on public.barcode_mappings for select using (auth.uid() = user_id);
create policy "barcode_owner_insert" on public.barcode_mappings for insert with check (auth.uid() = user_id);
create policy "barcode_owner_update" on public.barcode_mappings for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "barcode_owner_delete" on public.barcode_mappings for delete using (auth.uid() = user_id);

-- ----------------------------------------------------------------------------
-- recipes  (per-user library; previous SQLite version was global+seeded but the
-- uncommitted meal-plan diff already removed the seed)
-- ----------------------------------------------------------------------------
create table public.recipes (
  id           bigint generated by default as identity primary key,
  user_id      uuid not null references auth.users(id) on delete cascade,
  name         text not null,
  ingredients  text not null,
  prep_time    text,
  servings     integer,
  instructions text,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create index idx_recipes_user on public.recipes(user_id);
create unique index uq_recipes_user_name_lower on public.recipes(user_id, lower(name));

alter table public.recipes enable row level security;
create policy "recipes_owner_select" on public.recipes for select using (auth.uid() = user_id);
create policy "recipes_owner_insert" on public.recipes for insert with check (auth.uid() = user_id);
create policy "recipes_owner_update" on public.recipes for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "recipes_owner_delete" on public.recipes for delete using (auth.uid() = user_id);

-- ----------------------------------------------------------------------------
-- meal_plans  (UNIQUE on (user, date, meal_type) fixes the drag-drop duplicate
-- slot bug the audit identified in the uncommitted diff)
-- ----------------------------------------------------------------------------
create table public.meal_plans (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null references auth.users(id) on delete cascade,
  plan_date   date not null,
  meal_type   text not null check (meal_type in ('breakfast','lunch','dinner')),
  meal_name   text not null,
  recipe_id   bigint references public.recipes(id) on delete set null,
  is_favorite boolean not null default false,
  notes       text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  unique (user_id, plan_date, meal_type)
);

create index idx_meal_plans_user_date on public.meal_plans(user_id, plan_date);

alter table public.meal_plans enable row level security;
create policy "meal_plans_owner_select" on public.meal_plans for select using (auth.uid() = user_id);
create policy "meal_plans_owner_insert" on public.meal_plans for insert with check (auth.uid() = user_id);
create policy "meal_plans_owner_update" on public.meal_plans for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "meal_plans_owner_delete" on public.meal_plans for delete using (auth.uid() = user_id);

-- ----------------------------------------------------------------------------
-- ai_usage_log  (drives the per-user monthly OpenAI quota; rows are written
-- atomically by the try_consume_ai_quota function in 0002_ai_quota_function.sql)
-- ----------------------------------------------------------------------------
create table public.ai_usage_log (
  id              bigint generated by default as identity primary key,
  user_id         uuid not null references auth.users(id) on delete cascade,
  request_type    text not null,
  item_name       text,
  response_days   integer,
  response_note   text,
  cost_estimate_cents integer,
  created_at      timestamptz not null default now()
);

create index idx_ai_usage_user_created on public.ai_usage_log(user_id, created_at desc);
create index idx_ai_usage_user_type_created on public.ai_usage_log(user_id, request_type, created_at desc);

alter table public.ai_usage_log enable row level security;
-- Only the user themself can read their own log; writes happen via the API
-- using the user JWT (the function below runs in SECURITY INVOKER context).
create policy "ai_usage_owner_select" on public.ai_usage_log for select using (auth.uid() = user_id);
create policy "ai_usage_owner_insert" on public.ai_usage_log for insert with check (auth.uid() = user_id);

-- ----------------------------------------------------------------------------
-- updated_at trigger for tables that have one
-- ----------------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create trigger trg_inventory_items_updated_at
  before update on public.inventory_items
  for each row execute function public.set_updated_at();

create trigger trg_recipes_updated_at
  before update on public.recipes
  for each row execute function public.set_updated_at();

create trigger trg_meal_plans_updated_at
  before update on public.meal_plans
  for each row execute function public.set_updated_at();

-- ----------------------------------------------------------------------------
-- Seed default categories  (idempotent via ON CONFLICT)
-- ----------------------------------------------------------------------------
insert into public.categories (name, icon, color) values
  ('Dairy',      '🥛', '#FFEB3B'),
  ('Produce',    '🥬', '#4CAF50'),
  ('Meat',       '🥩', '#F44336'),
  ('Seafood',    '🐟', '#03A9F4'),
  ('Frozen',     '❄️', '#00BCD4'),
  ('Pantry',     '🥫', '#FF9800'),
  ('Beverages',  '🥤', '#9C27B0'),
  ('Snacks',     '🍿', '#E91E63'),
  ('Condiments', '🧂', '#795548'),
  ('Bakery',     '🍞', '#FFC107'),
  ('Fruit',      '🍎', '#F2B2B2'),
  ('Other',      '📦', '#9E9E9E')
on conflict (name) do nothing;
