import type { VercelRequest, VercelResponse } from '@vercel/node';

// AUTO-GENERATED by scripts/migrate (one-time). Single Vercel Serverless
// Function that routes every /api/* request to the matching handler under
// _routes/. Consolidating to one function keeps the deployment within the
// Hobby plan's 12-function limit. Handlers are unchanged: path params are
// injected into req.query exactly as Vercel's filesystem router would.

import h0 from "./_routes/ai/expiration-suggest.js";
import h1 from "./_routes/ai/receipt-scan.js";
import h2 from "./_routes/barcode-mappings/[barcode].js";
import h3 from "./_routes/barcode-mappings/index.js";
import h4 from "./_routes/categories/[id].js";
import h5 from "./_routes/categories/index.js";
import h6 from "./_routes/cron/check-expirations.js";
import h7 from "./_routes/health.js";
import h8 from "./_routes/inventory/[id].js";
import h9 from "./_routes/inventory/[id]/batches/[batchId].js";
import h10 from "./_routes/inventory/[id]/batches/deduct.js";
import h11 from "./_routes/inventory/[id]/batches/index.js";
import h12 from "./_routes/inventory/[id]/images.js";
import h13 from "./_routes/inventory/[id]/usage.js";
import h14 from "./_routes/inventory/by-barcode/[barcode]/images.js";
import h15 from "./_routes/inventory/images/[imageId].js";
import h16 from "./_routes/inventory/index.js";
import h17 from "./_routes/locations/[id].js";
import h18 from "./_routes/locations/index.js";
import h19 from "./_routes/meal-plans/[id].js";
import h20 from "./_routes/meal-plans/index.js";
import h21 from "./_routes/push/subscribe.js";
import h22 from "./_routes/push/test.js";
import h23 from "./_routes/recipes/[id].js";
import h24 from "./_routes/recipes/index.js";
import h25 from "./_routes/shopping-list/[id].js";
import h26 from "./_routes/shopping-list/index.js";
import h27 from "./_routes/statistics/dashboard.js";
import h28 from "./_routes/uploads/read.js";
import h29 from "./_routes/uploads/sign.js";
import h30 from "./_routes/waste/[id].js";
import h31 from "./_routes/waste/from-item.js";
import h32 from "./_routes/waste/index.js";

type Handler = (req: VercelRequest, res: VercelResponse) => unknown | Promise<unknown>;

interface Route {
  segments: string[]; // literal segment or ':param'
  handler: Handler;
}

const routes: Route[] = [
  { segments: ["ai","expiration-suggest"], handler: h0 },
  { segments: ["ai","receipt-scan"], handler: h1 },
  { segments: ["barcode-mappings",":barcode"], handler: h2 },
  { segments: ["barcode-mappings"], handler: h3 },
  { segments: ["categories",":id"], handler: h4 },
  { segments: ["categories"], handler: h5 },
  { segments: ["cron","check-expirations"], handler: h6 },
  { segments: ["health"], handler: h7 },
  { segments: ["inventory",":id"], handler: h8 },
  { segments: ["inventory",":id","batches",":batchId"], handler: h9 },
  { segments: ["inventory",":id","batches","deduct"], handler: h10 },
  { segments: ["inventory",":id","batches"], handler: h11 },
  { segments: ["inventory",":id","images"], handler: h12 },
  { segments: ["inventory",":id","usage"], handler: h13 },
  { segments: ["inventory","by-barcode",":barcode","images"], handler: h14 },
  { segments: ["inventory","images",":imageId"], handler: h15 },
  { segments: ["inventory"], handler: h16 },
  { segments: ["locations",":id"], handler: h17 },
  { segments: ["locations"], handler: h18 },
  { segments: ["meal-plans",":id"], handler: h19 },
  { segments: ["meal-plans"], handler: h20 },
  { segments: ["push","subscribe"], handler: h21 },
  { segments: ["push","test"], handler: h22 },
  { segments: ["recipes",":id"], handler: h23 },
  { segments: ["recipes"], handler: h24 },
  { segments: ["shopping-list",":id"], handler: h25 },
  { segments: ["shopping-list"], handler: h26 },
  { segments: ["statistics","dashboard"], handler: h27 },
  { segments: ["uploads","read"], handler: h28 },
  { segments: ["uploads","sign"], handler: h29 },
  { segments: ["waste",":id"], handler: h30 },
  { segments: ["waste","from-item"], handler: h31 },
  { segments: ["waste"], handler: h32 },
];

function getParts(req: VercelRequest): string[] {
  const raw = (req.query as Record<string, string | string[] | undefined>).path;
  let parts: string[];
  if (Array.isArray(raw)) parts = raw;
  else if (typeof raw === 'string' && raw.length) parts = raw.split('/');
  else {
    const urlPath = (req.url ?? '').split('?')[0];
    parts = urlPath
      .replace(/^\/+/, '')
      .replace(/^api\/?/, '')
      .split('/')
      .filter(Boolean);
  }
  return parts.map((p) => {
    try {
      return decodeURIComponent(p);
    } catch {
      return p;
    }
  });
}

// Match parts against the route table. Among same-length matches, the route
// with the most literal (non-param) segments wins, so static routes always
// beat dynamic ones (e.g. /waste/from-item over /waste/:id) regardless of order.
function matchRoute(
  parts: string[],
): { handler: Handler; params: Record<string, string> } | null {
  let best: { handler: Handler; params: Record<string, string>; score: number } | null = null;
  for (const route of routes) {
    if (route.segments.length !== parts.length) continue;
    const params: Record<string, string> = {};
    let score = 0;
    let ok = true;
    for (let i = 0; i < parts.length; i++) {
      const seg = route.segments[i];
      if (seg.startsWith(':')) params[seg.slice(1)] = parts[i];
      else if (seg === parts[i]) score++;
      else {
        ok = false;
        break;
      }
    }
    if (!ok) continue;
    if (!best || score > best.score) best = { handler: route.handler, params, score };
  }
  return best ? { handler: best.handler, params: best.params } : null;
}

export default async function dispatch(req: VercelRequest, res: VercelResponse) {
  const parts = getParts(req);
  const match = matchRoute(parts);
  if (!match) {
    res
      .status(404)
      .json({ error: { code: 'NOT_FOUND', message: `No route for /api/${parts.join('/')}` } });
    return;
  }
  const q = req.query as Record<string, string | string[]>;
  for (const [k, v] of Object.entries(match.params)) q[k] = v;
  await match.handler(req, res);
}
